Table Pizzas {
   id int pk
   priceCents int
   name varchar
}

Table Categories {
  id int pk
  name varchar
}

Table CategoryPizza {
  pizzaId int pk [ref :> Pizzas.id]
  categoryId int pk [ref :> Categories.id]
}

Table Ingredients {
  id int pk
  name varchar
}

Table IngredientPizza {
  ingredientId int pk [ref :> Ingredients.id]
  pizzaId int pk [ref :> Pizzas.id]
}

Table Orders {
  id int pk
  orderTime time
  orderDate date

}

Table OrderItem {
  orderId int pk [ref :> Orders.id]
  pizzaId int pk [ref :> Pizzas.id]
  count int
}

Table PizzaSizes {
  id int pk
  pizzaId int [ref: > Pizzas.id]
  size varchar
  priceCents int
}

