version: 2

sources:
  - name: raw
    schema: main
    tables:
      - name: raw_student_enrolments
        description: Raw student enrolment events
      - name: raw_programmes
        description: Raw programme reference data
